name: Create and publish a Docker image

on:
  push:
  workflow_dispatch:

# Defines two custom environment variables for the workflow.
# These are used for the Container registry domain, and a name for the Docker image that this workflow builds.
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

# There is a single job in this workflow.
# It's configured to run on the latest available version of Ubuntu.
jobs:
  build-app-images:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: 'spacy:latest'
            context: 'python/spacy/'
          - image: 'spacy-gpu:latest'
            context: 'python/spacy/'
          - image: 'cuda-535-notebook'
            context: 'jupyter/python-cuda-535'
          - image: 'python-minimal-s3'
            context: 'jupyter/python-minimal-s3'

    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/ucrel/${{ matrix.image }}